[project]
name = "uv-template-ramankevich"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "pandas>=3.0.6",
    "pytest>=9.1.1",
    "requests>=2.34.2",
]

[project.scripts]
uv-template-ramankevich = "uv_template_ramankevich:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
